import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import BookList from '../components/BookList'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon1.ico" />
      </Head>

      <main>
        <h1>
          Welcome
        </h1>
      </main>
        <BookList />
    </div>
  )
}
