import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
// import BookList from '../components/BookList'
import { gql } from '@apollo/client';
import client from "../apollo-client";

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
    query RootQueryType {
      books {
        name
        genre
      }
    }
  `,
  });

  return {
    props: {
      books: data.books,
    },
  };
}

export default function Home({ books }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon1.ico" />
      </Head>

      <main>
        <h1>
          Book List
        </h1>
        <div >
          {books.map((book) => (
            <div key={book.id} > <p> {book.name} </p> </div>
          ))}
        </div>
      </main>
    </div>
  )
}
